# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :release do
    # increment_version_number
    get_certificates(
      development: false,
      username: "xxx@gmail.com",
      team_id: "xxx",
      keychain_path: "~/Library/Keychains/ios-build.keychain-db",
      keychain_password: "xxx"
    )
    get_provisioning_profile(
      development: false,
      provisioning_name: "xxx"
    )
    build_ios_app(
      workspace: "xxx.xcworkspace",
      configuration: "Release",
      scheme: "xxx",
      silent: true,
      clean: true,
      output_directory: "./build",
      output_name: "xxx.ipa",
      archive_path: "./build"
    )
  end
  lane :beta do
    sigh(
      development: true,
      username: "xxx@gmail.com",
      team_id: "xxx",
      app_identifier: "com.xxx",
      readonly: true
    )
    build_ios_app(
      workspace: "xxx.xcworkspace",
      configuration: "Debug",
      scheme: "xxx",
      silent: true,
      clean: true,
      output_directory: "./build",
      output_name: "xxxx.ipa",
      export_method: "development"
    )
  end
end
